[versions]
compileSdk = "36"
minSdk = "26"
targetSdk = "35"
ndk = "28.2.13676358"
gradle = "8.13.1"

#kotlin
kotlin = "2.0.0"
kotlinKsp = "2.0.0-1.0.21"
kotlinSerialization = "1.7.1"
kotlinReflect = "2.0.0"
coroutines = "1.10.2"

#android
androidx = "1.7.1"
cardView = "1.0.0"
recyclerView = "1.4.0"
recyclerViewSelection = "1.2.0"
constraint = "2.2.1"
ktx = "1.17.0"
fragmentKtx = "1.8.9"
biometric = "1.1.0"
androidWorkManager = "2.11.0"
androidDocumentFile = "1.1.0"

#compose
composeMaterial = "1.10.0"
composeMaterial3 = "1.4.0"
composeUi = "1.10.0"
composeUiTooling = "1.10.0"
composeUiToolingPreview = "1.10.0"
composeNavigation = "2.9.6"
composeCompiler = "2.0.0"
compose = "1.10.0"
composeConstrainLayout = "1.1.1"

#dagger
dagger = "2.57.1"

#room
room = "2.6.1"

#moxy
moxy = "2.2.2"

#koin
koin = "4.1.1"

#firebase
firebaseCore = "21.1.1"
firebaseConfig = "23.0.1"
firebaseMessaging = "25.0.1"
firebaseCrashlytics = "20.0.3"

#livedata
lifecycle = "2.10.0"

#google
playServieAuth = "21.4.0"
playReview = "2.0.2"
material = "1.13.0"
gson = "2.13.2"
safetynet = "18.1.0"
app-update = "2.1.0"
text-recognition = "16.0.1"
object-detection = "17.0.2"

jackson = "2.18.3"

rxjava = "2.1.1"

retrofit = "3.0.0"
retrofitKtSerialization = "1.0.0"

firebaseCrashlyticsGradle = "3.0.6"
googleServices = "4.4.4"

#other
phoneNumber = "8.13.52"
facebookLogin = "18.0.2"
pageIndicator = "v.1.0.3"
glide = "4.16.0"
glideOkHttpIntegration = "4.16.0"
glideCompose = "1.0.0-beta01"
photoView = "2.3.0"
colorPicker = "2.3.0"
customTabs = "1.9.0"

#tests
junit = "4.13.2"
junitEx = "1.3.0"
mockk = "1.13.17"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx" }
recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
recyclerViewSelection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerViewSelection" }
cardView = { module = "androidx.cardview:cardview", version.ref = "cardView" }
constraint = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint" }
ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidWorkManager = { module = "androidx.work:work-runtime-ktx", version.ref = "androidWorkManager" }
androidDocumentFile = { module = "androidx.documentfile:documentfile", version.ref = "androidDocumentFile" }
androidCustomTabs = { module = "androidx.browser:browser", version.ref = "customTabs" }

#compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiTooling" }
compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUiToolingPreview" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-constraint-layout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstrainLayout" }

#google
google-playServiceAuth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServieAuth" }
google-playReview = { module = "com.google.android.play:review", version.ref = "playReview" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
google-safetynet = { module = "com.google.android.gms:play-services-safetynet", version.ref = "safetynet" }
google-update = { module = "com.google.android.play:app-update-ktx", version.ref = "app-update" }
google-ml-text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "text-recognition" }
google-ml-text-recognitionchinese = { module = "com.google.mlkit:text-recognition-chinese", version.ref = "text-recognition" }
google-ml-objects-detection = { module = "com.google.mlkit:object-detection", version.ref = "object-detection" }

#kotlin
kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }

#dagger
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

#room
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

#moxy
moxy = { module = "com.github.moxy-community:moxy-androidx", version.ref = "moxy" }
moxy-material = { module = "com.github.moxy-community:moxy-material", version.ref = "moxy" }
moxy-compiler = { module = "com.github.moxy-community:moxy-compiler", version.ref = "moxy" }
moxy-ktx ={ module = "com.github.moxy-community:moxy-ktx", version.ref = "moxy" }

#koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

#firebase
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebaseCore" }
firebase-config = { module = "com.google.firebase:firebase-config", version.ref = "firebaseConfig" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }

#retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}
retrofit-xml = { module = "com.squareup.retrofit2:converter-simplexml", version.ref = "retrofit"}
retrofit-rx = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit"}
retrofit-kotlin-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKtSerialization" }

#jacson
jackson = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

#rxjava
rx-java = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxjava" }
rx-relay = { module = "com.jakewharton.rxrelay2:rxrelay", version.ref = "rxjava" }

#lifecycle
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

#other
phoneNumber = { module = "io.michaelrocks:libphonenumber-android", version.ref = "phoneNumber" }
facebookLogin = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }
pageIndicator = { module = "com.github.romandanylyk:pageindicatorview", version.ref = "pageIndicator" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideKsp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glideOkhttp = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glideOkHttpIntegration" }
glideCompose = { module = "com.github.bumptech.glide:compose", version.ref = "glideCompose" }
photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoView" }
colorPicker = { module = "com.github.skydoves:colorpickerview", version.ref = "colorPicker" }

#tests
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitEx" }

[plugins]
android-library = { id = "com.android.library", version.ref = "gradle" }
android-application = { id = "com.android.application", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
kotlin-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composeCompiler" }
